export const FETCH_HOTELS_REQUEST = "FETCH_HOTELS_REQUEST";
export const FETCH_HOTELS_SUCCESS = "FETCH_HOTELS_SUCCESS";
export const FETCH_HOTELS_FAILURE = "FETCH_HOTELS_FAILURE";

export const FETCH_HOTEL_IMAGES_REQUEST = "FETCH_HOTEL_IMAGES_REQUEST";
export const FETCH_HOTEL_IMAGES_SUCCESS = "FETCH_HOTEL_IMAGES_SUCCESS";
export const FETCH_HOTEL_IMAGES_FAILURE = "FETCH_HOTEL_IMAGES_FAILURE";

export const FETCH_HOTEL_COMMENTS_REQUEST = "FETCH_HOTEL_COMMENTS_REQUEST";
export const FETCH_HOTEL_COMMENTS_SUCCESS = "FETCH_HOTEL_COMMENTS_SUCCESS";
export const FETCH_HOTEL_COMMENTS_FAILURE = "FETCH_HOTEL_COMMENTS_FAILURE";

export const SET_FILTERS = "SET_FILTERS";

export const SET_UI_MODE = "SET_UI_MODE";
